### ISSUE TITLE
Investigate whether to include site links for all languages in the filtered Wikipedia dump

### ISSUE THREAD

**Issue by davidebbo** [OneZoom/tree-build#23]
Currently, we only include the site links for English. For the rest, it only keeps the key to mark the existence of the language. e.g.

```json
"sitelinks": {
    "enwiki": {
        "site": "enwiki",
        "title": "Lion",
        "badges": [
            "Q17437796"
        ]
    },
    "dewiki": {},
    "frwiki": {},
    "eswiki": {}
}
```

The suggestion is to measure how much bigger the file would get if we include the details for all languages.

**Comment by davidebbo** [comment]
Looking at the 3 fields in there:
- The site seems redundant, as it's always set to a value that matches the key name.
- Title is I think the key field we care about
- What are badges? It seems that when it's set, the value comes from a small set, like [Q17437796](https://www.wikidata.org/wiki/Q17437796) or [Q70893996](https://www.wikidata.org/wiki/Q70893996).

**Comment by davidebbo** [comment]
I experimented with this. When keeping the full `sitelinks` for all languages:
- The total file size of the filtered dump goes from 1,273,286,854 to 1,824,406,269 bytes, so a 43% increase
- There are 3,691,334 lines, so that makes the average line length go from 345 to 494 bytes.

It's a one-line code change in `generate_filtered_wikidata_dump`.

**Comment by hyanwong** [comment]
That's great. I'm sure we can drop "badges", for what it's worth.

A 43% increase seems like a worthwhile tradeoff for generating to all languages, to me?

**Comment by davidebbo** [comment]
> A 43% increase seems like a worthwhile tradeoff for generating to all languages, to me?

Yes, I agree, and we can further reduce it if we only keep the title (basically the common name?) field.

**Comment by hyanwong** [comment]
Great. I don't think it *has* to be the common name, by the way. It's just that for the popular species the first page that is created for that species in any particular language tends to use the common name. Here's an English example that doesn't use a common name: https://en.wikipedia.org/wiki/Osedax

**Comment by hyanwong** [comment]
Yes, I agree with this.

**Comment by davidebbo** [comment]
I decided to add a `--dont_trim_sitelinks` flag to make this behavior optional. On my machine, I like to keep the filtered file as small and fast as possible, but those who want to keep the sitelinks titles for all languages can.

**Comment by hyanwong** [comment]
Great. That's a good idea. Fast files for testing are really useful, I agree. Thanks.

**Comment by davidebbo** [comment]
That change is in 8706ef4cafa81fae2dc861ec9459854a4eafb488
