### ISSUE TITLE
Investigate why some popular species are missing a common name

### ISSUE THREAD

**Issue by davidebbo** [OneZoom/tree-build#24]
A good example of this is the Aardwolf (Proteles cristatus). See https://www.onezoom.org/life/@Hyaenidae=397138).

At this point, I'm not familiar with the logic that gets common names, but it would be worth digging into it.

**Comment by davidebbo** [comment]
Closing because:
- We decided not to make vernacular names a concern for this repo
- @hyanwong hand fixed the Aardwolf. Though side note: the image that got added is probably worse than no image. Shows a bunch of animals, and I'm not sure any of them is in fact an Aardwolf! 😆 Wish we could use the one from Wikimedia instead...

**Comment by hyanwong** [comment]
That was the default non-cc-nc one from EoL. We can specifically pick another EoL photo instead, quite easily, by finding the EoL media ID we want from https://eol.org/pages/925982/media. E.g. https://eol.org/media/29342707

**Comment by davidebbo** [comment]
Yes, that image would be better. Though of course, our focus should be on having automated logic that results in a quality outcome, since hand fixing is not very scalable.

Anyway, would it be best to take the discussion to a new issue on OZtree, since we deemed that it belongs there? Browsing randomly around the tree, I feel there are a lot of species that either have a [poorly selected image](https://www.onezoom.org/life/@Potamochoerus=995191?img=best_any&anim=jump#x816,y-889,w3.5791) or [no image at all](https://www.onezoom.org/life/@Phacochoerus_aethiopicus=983664?img=best_any&anim=jump#x1423,y-64,w1.7209), so it's a fairly widespread issue that hopefully we can improve in a more global way.

**Comment by hyanwong** [comment]
> Yes, that image would be better. Though of course, our focus should be on having automated logic that results in a quality outcome, since hand fixing is not very scalable.

Yes, absolutely. I wonder if there are freely available image-quality-assessing algorithms?

**Comment by hyanwong** [comment]
> Anyway, would it be best to take the discussion to a new issue on OZtree, since we deemed that it belongs there? 

Good point, I'll open up a new issue and give some background there.

**Comment by davidebbo** [comment]
> I wonder if there are freely available image-quality-assessing algorithms?

Personal opinion: it's best to rely on an outside source that has already assessed image quality (whether via human curation or some automation), so we don't need to get into that business. Ideally, EOL would do a better job with that. I need to look more into what they offer.

**Comment by hyanwong** [comment]
Yes, I agree, that would be much better. Sadly that's not been done (yet) on wikipedia or EoL. I'm sure that EoL would be *very* keen if we could cook something up for them (I originally wrote their Wikimedia harvester for them, as part of an attempt to improve images used on OneZoom, so they are happy to have contributors, but if could be a lot of work).

**Comment by davidebbo** [comment]
> Sadly that's not been done (yet) on wikipedia or EoL

My impression is that the main image for a species on Wikipedia is typically high quality, and was likely human curated. But it sounds like the problem with Wikipedia is more on the licence side, i.e. we can't generally just use their primary image? That seems unfortunate, given that we in fact do display their images *indirectly* when we pop up the Wikipedia preview, but still technically within the OneZoom site. I'm sure there is a subtle legal distinction that I don't understand :)

Anyway, it'll be easier to discuss directly in a follow up meeting.

**Comment by hyanwong** [comment]
There are 2 issue. Firstly, we don't know if the licence on the wikipedia page is acceptable. Secondly, we don't want to get the image from wikipedia, but wikidata (as different language wikipedias may have different images etc., and we want a standardised way to get an image).

For the aardwolf, there is an "image" section on wikidata (see https://www.wikidata.org/wiki/Q185295, about 3 categories down). However, there are 2 images here, one close up and one far away with a bit more habitat. I'm not sure how we would decide on which to take?

**Comment by davidebbo** [comment]
Interestingly, for both wikipedia and wikidata, if you click the image, and More Details, you end up on the same *wikimedia* resource: https://commons.wikimedia.org/wiki/File:Proteles_cristatus1.jpg. So in that sense, you'd never really be using a file stored in a language specific wikipedia. Instead, US wikipedia would only be used as a way to get a 'good' link to language agnostic wikimedia file.

Also, on https://commons.wikimedia.org/wiki/File:Proteles_cristatus1.jpg, there is a 'structured data' section which includes links to licences. So in theory, we could check if the licence is in a known set without much parsing.

**Comment by lentinj** [comment]
> However, there are 2 images here, one close up and one far away with a bit more habitat. I'm not sure how we would decide on which to take?

The top one has a "preferred" rank (the tiny lift-buttons to the left of the image), presumably that's linked with what the wikipedia page displays. [This is visible via the API](https://www.wikidata.org/w/api.php?action=wbgetentities&ids=Q185295), look for "Proteles cristatus1.jpg" and you see ``"rank": "preferred"``. No idea what happens if you have more than one preferred image (or if that's possible).

**Comment by davidebbo** [comment]
Great find @lentinj on the 'preferred' bit!

Note that the main Wikipedia does not appear to common deterministically from this. e.g. looking at the Alpaca:
- https://www.wikidata.org/wiki/Q81564 has just one image, not marked preferred
- https://en.wikipedia.org/wiki/Alpaca is using it
- https://de.wikipedia.org/wiki/Alpaka (German) uses a different image, not included in wikidata

But regardless, a basic algorithm of "Take the first preferred from wikidata, otherwise take the first regular" probably yields decent results (if we can get past the licence part).

**Comment by hyanwong** [comment]
> Interestingly, for both wikipedia and wikidata, if you click the image, and More Details, you end up on the same _wikimedia_ resource: https://commons.wikimedia.org/wiki/File:Proteles_cristatus1.jpg. So in that sense, you'd never really be using a file stored in a language specific wikipedia. Instead, US wikipedia would only be used as a way to get a 'good' link to language agnostic wikimedia file.

Yes, all the images are stored on wiki*media* commons. But different language wikipedias may use different images, so it would be best to use the wikidata recommended one (and, in addition, it may be hard to extract *which* image on a page is representative.

> Also, on https://commons.wikimedia.org/wiki/File:Proteles_cristatus1.jpg, there is a 'structured data' section which includes links to licences. So in theory, we could check if the licence is in a known set without much parsing.

Aha. The structure data tab is a new one. I previously had to use the categories at the bottom of the page. This could be useful (but we would need to download the wikimedia commons [dump](https://dumps.wikimedia.org/commonswiki/20231120/) (21GB b2zipped), or do multiple API queries, to get the information, I suppose, and parse the author of the image etc.)
