### ISSUE TITLE
Minor test bug: deprecation warning for \D

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/tree-build#25]
When I run purest, I get:

```
oz_tree_build/utilities/temp_helpers.py:16
  /Users/yan/Documents/GitHub/tree-build/oz_tree_build/utilities/temp_helpers.py:16: DeprecationWarning: invalid escape sequence '\D'
    quick_byte_match = re.compile('numeric-id":(?:{})\D'.format(regexp_match))
```

**Comment by davidebbo** [comment]
I'm actually not familiar with purest. Do you have a pointer on how to set this up?

Note that this sequence was carried from the OZtree repo ([here](https://github.com/OneZoom/OZtree/blob/2d6a8487ff6133b473575e258ec3435169eec8fc/OZprivate/ServerScripts/TaxonMappingAndPopularity/OTT_popularity_mapping.py#L606)).

Regardless, the warning seems legit. I'm guessing that the intention was to use the **regex** `\D`, which means any non-digit character. But then the Python string would need to have `\\D`. But we should make sure this doesn't break something before touching this.

**Comment by hyanwong** [comment]
I'm a bit surprised that the regex was working previously, if "\D" was being interpreted as some sort of special character.

**Comment by lentinj** [comment]
> I'm a bit surprised that the regex was working previously, if "\D" was being interpreted as some sort of special character.

As the string escape "\D" isn't a thing, it'll fall through and be treated as "\D", after which it can be picked up by the regex engine as you were hoping:

```
>>> "\n"
'\n'
>>> "\D"
'\\D'
```

...so this is just a warning to fix, and unlikely to have unexpected results.

**Comment by hyanwong** [comment]
Ah, That's great, thanks a lot for the info Jamie. Seems like a trivial fix then.

**Comment by davidebbo** [comment]
Thanks @lentinj, they are indeed identical:

```
>>> "ABC\DE"
'ABC\\DE'
>>> "ABC\\DE"
'ABC\\DE'
``

I'll just fix it.
