### ISSUE TITLE
Add David's tests and code to this repo

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/tree-build#3]
Once #1 is done, we should add @davidebbo's code here, and also any unit tests to get this working. It would be nice to get automated unit testing and CI set up on this repo too. I will see if I can get a colleague to help with this.

**Comment by davidebbo** [comment]
Everything works well using these techniques. `console_scripts` was the big thing that I needed to expose different entry points from the package. Thanks again Jamie.

I've updated my test repo https://github.com/davidebbo/python-misc, but before sending a PR, we should discuss the overall shape that we want this new tree-build repo to have, as well as how much we want to bring over from the main repo.

e.g. I would think that most of what's in [OZprivate/data](https://github.com/OneZoom/OZtree/tree/main/OZprivate/data) belongs in this new repo. So maybe something like:

    repo root
      oz_tree_build
        # all the code to build the tree and other output files
      data
        # copy of OZprivate/data.
        # But maybe we can let go of the TreeArchive folder?
      tests
        # tests for code in oz_tree_build
      setup.cfg
      setup.py

@hyanwong and @jrosindell WDYT? Once we have a basic consensus on structure, we can start populating the repo.

**Comment by lentinj** [comment]
It seems likely that a [namespace package](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/) would one day be useful here, i.e. we'd want to do ``from oz.tree_build.newick import x`` to refer to stuff in here, amongst the other ``oz.*`` packages.

Admittedly we don't have any other oz packages yet, but I'd structure this as if we did in the future, i.e. ``oz/tree_build/``. Your tab key needed a workout anyway :)

**Comment by davidebbo** [comment]
@lentinj in this case, we specifically created a separate repo to focus on tree-build, so I'd think that we'll want to keep it specific to that. In the spirit of keeping the structure as simple as it can be, I'd vote for not having a namespace package for the time being (and it's easy to add this later if we need).

**Comment by davidebbo** [comment]
Got the initial code in: https://github.com/OneZoom/tree-build/pull/4
