### ISSUE TITLE
Discuss how to deal with non-extinct species from the fossil record

### ISSUE THREAD

**Issue by davidebbo** [OneZoom/tree-build#31]
I'm going to assume that among all species known from the fossil record, some are thought to be ancestors of current species, and hence are not extinct.

How would these be represented in the tree since they are effectively **non-leaf species**? Maybe it's simply about accepting that interior nodes can in fact represent species, rather than higher level taxa?

**Comment by hyanwong** [comment]
It is always assumed that no fossil species are actual ancestors (because it is logically impossible to actually prove that a fossil is an ancestor). The only real exception might be _Homo erectus_.

**Comment by davidebbo** [comment]
Ah, that is quite interesting. So some of them technically *might* be, but we always assume not.

Closing as there is no work needed here.
