### ISSUE TITLE
Add "rank" to the ordered nodes table

### ISSUE THREAD

**Issue by davidebbo** [OneZoom/tree-build#39]
From @hyanwong: *ordered_leaves should all have rank "species" or (possibly) "no rank - terminal", so we shouldn't need to include, but we could check and log any times they are not*

**Comment by davidebbo** [comment]
It appears that 'rank' is a [reserved word](https://www.tutorialspoint.com/can-we-use-rank-as-column-name-with-mysql8), which causes some friction.

Options:
1. Backquote it as `rank` in all SQL queries, which works but requires special casing this column
2. Name the column rnk instead

@hyanwong I'm tempted to go with 'rnk'. What do you think?

**Comment by hyanwong** [comment]
Ha. I can imagine why that was difficult to track down. Either `rnk`, or `taxonomic_rank` would be fine, IMO.

**Comment by davidebbo** [comment]
The basic change is quite simple. When it comes to
> ordered_leaves should all have rank "species" or (possibly) "no rank - terminal"

I'm running into an interesting case, where an ott is a subspecies for OpenTree, but a species for OneZoom:

```
563163	|	563165	|	Felis silvestris	|	species	|	ncbi:9683,gbif:7964291,irmng:10201332	|		|		|	
54743	|	563163	|	Felis silvestris bieti	|	subspecies	|	ncbi:458418,gbif:2435040,irmng:11269571	|		|	infraspecific	|	
```

For OneZoom, this OTT is a species ([Felis bieti](https://www.onezoom.org/life/@Felis_bieti=54743?img=best_any&anim=jump#x751,y495,w0.5914)), based on our bespoke trees.

But since we get the rank from OpenTree, we end up having a leaf that's marked as a subspecies.

None of that affects the new logic we care about, since this is only a sanity check that our leaves are indeed species.

Options:
1. Don't bother with this sanity check (or revisit later)
2. Loosen the sanity check to allow for leaves to be stamped as 'subspecies'

**Comment by davidebbo** [comment]
I went with 'rnk', and for now omitted the check on leaves.

Here is the distribution of ranks through the entire OneZoom tree:

```
mysql> SELECT rnk, COUNT(*) FROM ordered_nodes GROUP BY rnk ORDER BY COUNT(*) DESC;
+--------------------+----------+
| rnk                | COUNT(*) |
+--------------------+----------+
| NULL               |  2113842 |
| genus              |   104546 |
| family             |     7291 |
| subfamily          |     2908 |
| tribe              |     1665 |
| subgenus           |     1132 |
| order              |      842 |
| superfamily        |      640 |
| no rank            |      450 |
| subtribe           |      318 |
| suborder           |      246 |
| section            |      222 |
| class              |      216 |
| species group      |      148 |
| phylum             |      130 |
| infraorder         |       96 |
| subclass           |       94 |
| species subgroup   |       74 |
| superorder         |       37 |
| subphylum          |       17 |
| parvorder          |       16 |
| subsection         |       13 |
| infraclass         |       12 |
| superclass         |        8 |
| infrakingdom       |        6 |
| cohort             |        5 |
| kingdom            |        4 |
| no rank - terminal |        2 |
| infraphylum        |        2 |
| supertribe         |        2 |
| domain             |        2 |
| varietas           |        1 |
| superphylum        |        1 |
| subspecies         |        1 |
| subkingdom         |        1 |
| subcohort          |        1 |
+--------------------+----------+
```

Some are a bit odd, and maybe we'll need to only include those from a known set and ignore the rest.

**Comment by hyanwong** [comment]
Neat, thanks. I will talk about this with James next week.

**Comment by hyanwong** [comment]
Re _Felis bieti_, we will indeed have some things in the bespoke trees that are not of species rank in the OpenTree, but that's fine.

**Comment by davidebbo** [comment]
This is now complete.
