### ISSUE TITLE
Some key species end up with a raw popularity of zero

### ISSUE THREAD

**Issue by davidebbo** [OneZoom/tree-build#49]
This can happen when we use an outdated taxon.

One example is with the Snow Leopard:
- It's Panthera uncia, but our tree still has it as Uncia uncia.
- We end up mapping it to wikidata [Q12823232](https://www.wikidata.org/wiki/Q12823232) instead of [Q30197](https://www.wikidata.org/wiki/Q30197)
- But Q12823232 has no wikipedia sitelink for `en`, so we are not able to get any raw popularity for it.

Of course, it still gets some high popularity based on its ancestry, but it is getting short changed.

**Comment by davidebbo** [comment]
Fixing this would likely involve following synonyms, so that we end up treating Uncia uncia as Panthera uncia. The wiki dump line for Uncia uncia does point to Panthera uncia via P642:

    "P31": [
        {
            "qualifiers": {
                "P642": [
                    {
                        "datavalue": {
                            "value": {
                                "numeric-id": 30197
                            }
                        }
                    }
                ]
            }
        }
    ],

However, we're evidently not following this properly. I need to dig into this some more.

**Comment by davidebbo** [comment]
Here is another case that is more complex and also results in a missing raw popularity. The Bay cat (aka Bornean cat) has 3 wikidata entries:

1. [Pardofelis badia](https://www.wikidata.org/wiki/Q213044), marked as having as synonym 'Catopuma badia'. This is the entry that has all the wikipedia sitelinks
1. [Catopuma badia](https://www.wikidata.org/wiki/Q23772801), marked as having as synonym 'Felis badia'
1. [Felis badia](https://www.wikidata.org/wiki/Q23772812), marked as not having any synonyms

In OneZoom, we use the taxon Catopuma badia. The problem is that it leads only to Felis badia, which doesn't have the goods. So even if we follow synonyms, we get nowhere.

Maybe we need to catch this one from the other way around, relying on the Pardofelis badia -> Catopuma badia synonym link.

You would think that wikidata would automatically make any synonym symmetric, but I guess that's too much to ask :(

**Comment by davidebbo** [comment]
Another weird case: [Leopardus pajeros](https://www.wikidata.org/wiki/Q311417) is the Pampas cat.

Problem is that the wikidata entry has the english link linking to Leopardus_pajeros (which is a redirect), instead of to the main Pampas cat page: `"enwiki": { "title": "Leopardus pajeros" }`. So we end up looking up `Leopardus pajeros` in the Page Count file, and not finding anything, because all the hits are with the Pampas cat entry.

This is a completely different case from above, as it doesn't relate to needing to follow wikidata synonyms.

**Comment by hyanwong** [comment]
>  has the english link linking to Leopardus_pajeros (which is a redirect)

So we can either change the link in Wikidata and/or somehow keep redirects in the wikipedia dump, and follow those?

I seem to remember that I did do a bit of redirect-following in my original wikimedia parser, but I think I didn't think about that case on wikipedia.

Yan

**Comment by davidebbo** [comment]
> change the link in Wikidata

Interestingly, if you look at the links on https://www.wikidata.org/wiki/Q311417, next to 'en', there is a little arrow symbol. If you hover over it, it says "**intentional** sitelink to redirect". I'm not sure what the reasoning is, as in most cases, the link is to the main page with no redirects.

> somehow keep redirects in the wikipedia dump, and follow those

The wikiDATA dump doesn't know about redirects afaik. It just has wikiPEDIA links, which sometimes happen to redirect. So I'm not sure if we can get the redirect information, other than by actually making http requests to it, which is too painful/slow.

**Comment by hyanwong** [comment]
> The wikiDATA dump doesn't know about redirects afaik. It just has wikiPEDIA links, which sometimes happen to redirect. So I'm not sure if we can get the redirect information, other than by actually making http requests to it, which is too painful/slow.

Indeed, but perhaps the `enwiki-latest-page.sql.gz` file contains information on redirects?

**Comment by davidebbo** [comment]
> Indeed, but perhaps the `enwiki-latest-page.sql.gz` file contains information on redirects?

Yes, it has a `page_is_redirect` Boolean field (https://www.mediawiki.org/wiki/Manual:Page_table#page_is_redirect). I don't think it gives the redirection target, but at least if we had to make a request, that would greatly reduce the number of cases where it's needed.

**Comment by davidebbo** [comment]
My PR #58 addresses the Snow leopard and Bay cat issues above (and presumably many more like it).

It does not address the Pampas cat case (wikipedia redirect), which we should track as a separate issue.

**Comment by davidebbo** [comment]
I opened #59 to track the wiki redirect case. The rest of the issue is fixed, so closing this one.
