### ISSUE TITLE
Dealing with scripts that update the database

### ISSUE THREAD

**Issue by davidebbo** [OneZoom/tree-build#5]
After we get the basic bespoke tree logic in (#3), we need to think through how we want to tackle the rest, which is primarily what's currently in `CSV_base_table_creator.py` and `OTT_popularity_mapping.py`.

There are a couple possible approaches here:
1. Start by just copying the current logic as is, and evolve from there
2. Rethink the general problem space, and potentially come up with something quite different

@hyanwong and @jrosindell let's discuss.

**Comment by davidebbo** [comment]
`CSV_base_table_creator.py` and `OTT_popularity_mapping.py` functionality is in.

Still missing `picProcess.py` and `IUCNquery.py`. Though that raises an interesting question: should scripts like these that update the DB go in this repo? It gets tricky when they directly try to get a connection string from appconfig.ini using relative paths:
```py
default_appconfig_file = "../../../private/appconfig.ini"
```

**Comment by davidebbo** [comment]
I renamed it to refocus it on part that still needs discussion.

**Comment by hyanwong** [comment]
Yes, this is a good thing to discuss at 10am today

**Comment by davidebbo** [comment]
Per today's meeting, we decided that it was best to keep IUCN and Images as a OneZoom concern, and hence that it should not be part of this Tree Build repo. Closing this issue as a result.
