### ISSUE TITLE
get_open_trees_from_one_zoom.py emits warnings for missing taxa even if bespoke versions exist in `OT_required`

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/tree-build#53]
There are 2 files in https://github.com/OneZoom/tree-build/tree/main/data/OZTreeBuild/AllLife/OpenTreeParts/OT_required, labelled  `4795972.nwk` and `5205266.nwk` which are transferred in step 2 to the `OpenTree_all` directory, as a stand-in for taxa that are missing from the current OpenTree.

The get_open_trees_from_one_zoom.py script complains that it can't find these taxa on the OpenTree, which is true, but that warning doesn't need to be emitted, because we have provided substitutes. So the warning code needs a small tweak to avoid warning when taxa are present in the `OT_required` directory.

**Comment by davidebbo** [comment]
I think it's actually `build_oz_tree` and not `get_open_trees_from_one_zoom` that outputs this warning. I will look into it.

**Comment by hyanwong** [comment]
Thanks! I've almost fixed up the new tree. Just hitting a recursion problem (will post in a second)

**Comment by davidebbo** [comment]
Actually, I can't repro this. Here is the output when I run `get_open_trees_from_one_zoom`:

    WARNING:root:Could not find the following taxa: 385878, 747323, 5205266, 4795972, 523271

And when I run `get_open_trees_from_one_zoom`:

```
WARNING:root:Subtree file OpenTreeParts/OpenTree_all/523271.nwk does not exist
WARNING:root:Subtree file OpenTreeParts/OpenTree_all/747323.nwk does not exist
WARNING:root:Subtree file OpenTreeParts/OpenTree_all/385878.nwk does not exist
```

So I don't see anything about `4795972.nwk` and `5205266.nwk`.

**Comment by davidebbo** [comment]
I think you may have skipped step 2. When I skip it, `get_open_trees_from_one_zoom` gives:

```
WARNING:root:Subtree file OpenTreeParts/OpenTree_all/523271.nwk does not exist
WARNING:root:Subtree file OpenTreeParts/OpenTree_all/747323.nwk does not exist
WARNING:root:Subtree file OpenTreeParts/OpenTree_all/385878.nwk does not exist
WARNING:root:Subtree file OpenTreeParts/OpenTree_all/4795972.nwk does not exist
WARNING:root:Subtree file OpenTreeParts/OpenTree_all/5205266.nwk does not exist
```

**Comment by hyanwong** [comment]
Thanks for checking. I'm actually running from a new version of the files. I'll post a PR - just trying to track down a bug

**Comment by hyanwong** [comment]
I'm still getting the subtree error in stage  #54, and I don't believe I should be:

```
WARNING:root:Could not find the following taxa: 4795972, 5205266

```

**Comment by davidebbo** [comment]
I'm actually seeing 4 missing with all your changes:

    WARNING:root:Could not find the following taxa: 523271, 4795972, 5205266, 747323

Not sure why we see different things, but I'll dig into it

**Comment by hyanwong** [comment]
Hmm, that's weird. Both  https://tree.opentreeoflife.org/opentree/argus/opentree14.9@ott523271 and https://tree.opentreeoflife.org/opentree/argus/opentree14.9@ott747323 are ctenophores, and I have been fiddling with those. They shouldn't be being substituted, though.

**Comment by hyanwong** [comment]
Ah, I have an idea @davidebbo : you might need to clear out all the files from `data/OZTreeBuild/AllLife/BespokeTree/include_OTT3.6draft1/` before starting the pipeline. We should probably add that to the instructions.

**Comment by davidebbo** [comment]
Yes, that was it! Now down to the same as you: `4795972, 5205266`.

`Base.PHY` has `Aenigmarchaeota_ott4795972@` and `Diapherotrites_ott5205266@`, which don't exist in the open tree. So aren't these warnings expected?

**Comment by hyanwong** [comment]
They don't exist, but I grabbed them from a previous open tree version, and put them in the [OT_required](https://github.com/OneZoom/tree-build/tree/main/data/OZTreeBuild/AllLife/OpenTreeParts/OT_required) folder, from where they get copied in step 2. So we aren't missing them from the pipeline, just from v14.9 of the open tree. Since we have explicitly provided them as bespoke OpenTree additions, I don;t think we need to warn (or if we do, we should say "not in the open tree that you used, but have been provided separately."

It's not worth too much work thought. There are only two files! It's just nice to be able to complete without errors.

**Comment by davidebbo** [comment]
Oh, I get it now, sorry! As it stands, the tool is not smart enough to not look for those in the big tree. Maybe we don't need this warning at all, since if we were missing something, we should catch it in the next step (`build_oz_tree`).

**Comment by hyanwong** [comment]
It's a good point that we probably catch them later. I guess we can turn it into an "INFO" string instead.

**Comment by hyanwong** [comment]
> Yes, that was it! Now down to the same as you: 4795972, 5205266.

I added an `rm` command to the steps to clear out that directory, so we don;t have the same problem again.

**Comment by davidebbo** [comment]
Something in the latest CtenophoresWhelan2017.PHY is causing `add_ott_numbers_to_trees` to blow up: dendropy.dataio.newickreader.NewickReader.NewickReaderMalformedStatementError: Error parsing data source on line 1 at column 47: Malformed tree statement

You're not seeing this?

**Comment by hyanwong** [comment]
I made a typo and have force pushed a change. Do you want to grab the PR again and retry?

**Comment by davidebbo** [comment]
Yep, all good now! Bed time for me, so I'll continue tomorrow.

**Comment by hyanwong** [comment]
Great. Sorry not to have let you know about the update. I think I'm happy to merge this now.

**Comment by davidebbo** [comment]
Yes, please go ahead and merge if it all seems good!
