### ISSUE TITLE
Add CI testing to this repo

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/tree-build#68]
For the wiki & image bit testing, we will either need to mock the mysql database, or set up CI with a database we can point pymysql to, annoyingly. Unless you can think of a neat way round this @davidebbo ?

**Comment by hyanwong** [comment]
Actually, the sqlite stuff does this quite effectively, so I think we are set to go on getting CI working.

**Comment by hyanwong** [comment]
You can test this by doing `python -m pytest tests --conf-file tests/appconfig.ini`, and I think it should work offline and with no DB running.

**Comment by davidebbo** [comment]
Yes, I just tried and it runs great.

**Comment by hyanwong** [comment]
I will ask my colleague about the best way to set up CI, and follow up here.

**Comment by hyanwong** [comment]
Done in #93
