### ISSUE TITLE
Default testing to sqlite?

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/tree-build#70]
Now that we can also use a temporary sqlite database for testing the wiki harvester, should we do this by default? Or perhaps only in automated CI?

**Comment by davidebbo** [comment]
If it runs fine with sqlite, I'm all for it. Does that involve committing a db file into the repo?

**Comment by hyanwong** [comment]
The db file just gets regenerated every time the tests are run. There's no need to have stuff in the db beforehand, right? So all I do is make the 3 tables and run it.

It would be harder to test the clade functionality, though.

**Comment by davidebbo** [comment]
I haven't used sqlite much, but if that's how it works and it all happens super fast, then it's great.

For the clade, isn't it just a matter of also populating the `order_nodes` table?

**Comment by hyanwong** [comment]
Yes, it's just more rows to populate. But only a minimum of 3, so probably OK. 

It's easy enough to get the CI to use SQLite but use our own db when running tests from the command line. That way we will probably end up testing both DB backends regularly

**Comment by davidebbo** [comment]
Yes, makes sense to give coverage to mysql as well, since that's the real target.

**Comment by hyanwong** [comment]
Ok, so I'll close this, and we'll only use SQLite in CI (which is indeed required)
