### ISSUE TITLE
Switch to new Wiki page count files

### ISSUE THREAD

**Issue by davidebbo** [OneZoom/tree-build#8]
We're currently using page count files from https://dumps.wikimedia.org/other/pagecounts-ez/merged/, which stopped updating after August 2020. This is explained [here](https://dumps.wikimedia.org/other/pagecounts-ez/).

The new files are described on https://dumps.wikimedia.org/other/pageview_complete/readme.html, and can be downloaded from https://dumps.wikimedia.org/other/pageview_complete/.

They appear to be available in both daily and monthly form. Monthly is probably what we want, to avoid having to deal with too many files. e.g. the Jan 2023 files are in https://dumps.wikimedia.org/other/pageview_complete/monthly/2023/2023-01/.

There are 3 files for each month:

```
pageviews-202301-automated.bz2                     01-Feb-2023 04:23          1709531548
pageviews-202301-spider.bz2                        01-Feb-2023 04:23          6791967739
pageviews-202301-user.bz2                          01-Feb-2023 04:23          2751746994
```

I'm not seeing a description of what they each are, but I'm guessing it refers to the user agent of the requests, and that we probably want the user files.

Need to look at this in more depth later.

**Comment by davidebbo** [comment]
Looking at the 2023-01 user monthly file (pageviews-202301-user.bz2), lines look like this:

```
en.wikipedia Chimpanzees 7844 desktop 706 A18B18C18D17E44F22G18H26I21J36K34L15M25N13O23P23Q25R26S27T24U9V25W24X18Y23Z23[22\16]19^24_30
en.wikipedia Chimpanzees 7844 mobile-web 2634 A65B103C90D72E68F64G66H102I71J77K74L112M73N107O138P74Q66R77S103T90U82V101W74X87Y61Z83[90\129]93^73_69
```

Trying to make sense of it, per the [help page](https://dumps.wikimedia.org/other/pageview_complete/readme.html)
- 7844 is probably the page ID. Old format didn't have that, and maybe we should use this to correlate instead of the article title (feels more solid).
- Next field shows desktop vs mobile usage. We would probably add them up.
- Next field is hopefully the monthly usage. The help page says it's the 'daily total', but presumably that means monthly when looking at a monthly file? Though 3340 feels low for the monthly Chimpanzee hit count. In the 2020-07 file with the old format, it was 19813 (`en.z Chimpanzee 19813`), and usage should grow
- The odd field at the end gives the usage for each hour, again presumably aggregated over all days all the month. e.g. A65 means 65 between 00:00 and 01:00. No idea what `[90\129]93^73_69` at the end means.

We should make sure we really understand these files before trying to switch over.

**Comment by davidebbo** [comment]
Starting to look at this again. One observation is that the new format files are much larger. e.g. [the one for March](https://dumps.wikimedia.org/other/pageview_complete/monthly/2024/2024-03/) is 3.2GB. I'm sure most of it is not useful to us, and we can make it much smaller with our filtering logic. However, we still need to deal with the huge files to begin with.

That does make me wonder: given that we're dealing with species and not something like current events, why would there be a lot of popularity changes over time? If not, what do we gain from looking over many months of data? Wouldn't just looking over a few recent days be a good enough approximation?

**Comment by hyanwong** [comment]
Great that you are looking into this. Thanks @davidebbo.

You make a good point about page visits. However, certain species do show spikes in the monthly data (e.g. I have - weirdly - observed this with certain shark species in previous months). So I think that it would still be useful to average over months, but I think it's often not necessary to download the latest months data, as long as we have a good number (e.g. > 10) pre-processed files that we can use.

**Comment by hyanwong** [comment]
In other works, I'm not that warred about downloading 10 X 3 Gb files, as we should only ever need to do this once, and only need to run the filtering function once on the file, for all time. That's a bit different from e.g. the JSON file, for which we need to run the filtering whenever we want to update the wiki dataset.

**Comment by davidebbo** [comment]
On second thoughts, it does make sense that there would be spikes for some species. All it takes is an article that discusses one species, and there would be a significant surge lasting a week or so.

So to summarize:
- We want to look over 10 months to reduce temporal spikes
- Once we have those 10 months, we can stick with them for a very long time, because long term popularity should not vary too much
- We each need to filter those 10 files into much smaller files, after which we don't need to keep these 30+ GB of raw files. Or conceivably, if we can host files somewhere, I could do the filtering once and upload the filtered files for others. This could be done using a Github 'release'.

**Comment by davidebbo** [comment]
Here is my plan for this work:
- the preprocessing/filtering phase will:
  - only keep en.wikipedia items (same as with old format)
  - only keep items that we find in wikidata (same as with old format)
  - use a much simpler line format that just has 'Chimpanzee 78033', where the count is the sum of all the Chimpanzee lines. So we combine like lines, and get rid of all the superfluous fields, and in particular the really long hourly data. We didn't need to do that before, because there was only one line per item, and it was already quite simple.
- That results in a ~9MB uncompressed file for each month (vs 3.2GB compressed, so massively smaller).
- Anyone can run the filtering, but it takes quite a long time (between downloading and preprocessing). So we'll make the filtered files available for download somewhere, so that most people can just get those and get going quickly.

A couple things that are worth discussing:
1. We can drop all the entries with a very low hit count. e.g. if I ignore anything with <20 monthly hits (quite insignificant), the file size drops from 9MB to 3MB. Not sure if that would cause any meaningful loss in our popularity.
2. I could conceivably make an already summed up file available. i.e. it would have the sum of the data from many months in a single file. Here, you'd only need to download a single file and pass that to CSV_base_table_creator, instead of 'n' files.

I'm not convinced that either of these two optimizations are worthwhile, and they could always be done later.

@hyanwong please share your thoughts on this plan, and if it all sounds good I'll move forward.

**Comment by hyanwong** [comment]
I think this is done now isn't it @davidebbo, so we can close this?

**Comment by davidebbo** [comment]
Ah, yes it is!
