### ISSUE TITLE
"missing 3 required positional arguments: 'qid', 'tmp_path', and 'keep_rows'" when running tests

### ISSUE THREAD

**Issue by davidebbo** [OneZoom/tree-build#81]
I get these errors when running `pytest` on a clean `main`. I have not investigated.

```
ERROR tests/test_get_wiki_images.py::TestAPI::test_process_default_leaf - TypeError: TestAPI.setup() missing 3 required positional arguments: 'qid', 'tmp_path', and 'keep_rows'
ERROR tests/test_get_wiki_images.py::TestAPI::test_process_default_leaf_skip_images - TypeError: TestAPI.setup() missing 3 required positional arguments: 'qid', 'tmp_path', and 'keep_rows'
ERROR tests/test_get_wiki_images.py::TestAPI::test_process_clade - TypeError: TestAPI.setup() missing 3 required positional arguments: 'qid', 'tmp_path', and 'keep_rows'
```

**Comment by davidebbo** [comment]
The problem is that `setup` and `teardown` are magic names that `pytest` calls automatically. But in your case, you don't intend for this, since you are calling them explicitly. If I rename both those methods, then all the tests pass.

Not sure why you are not seeing this though. I have pytest 7.4.3.

**Comment by davidebbo** [comment]
Ok, issue goes away when moving to pytest 8.2.2. We should update the dependency version to mark that we need the newer one.

**Comment by hyanwong** [comment]
I would be happy to change the names of the functions (maybe that would be less confusing?)

**Comment by davidebbo** [comment]
Probably not necessary. I think as long as we update setup.cfg to have `pytest>=8.2`, no one will hit that. I hit it because I had installed it a while back, when presumably 7.x was the latest. Though it does raise the question of whether using ab open ended dependency (i.e. use the latest available) is a good idea, as it's likely to break things in the future as packages evolve.

**Comment by hyanwong** [comment]
I've changed the names in #82 anyway
